### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by goodmind** [goodmind/protoapp#1]
- [ ] Publish to [npm](https://www.npmjs.com/package/protoapp)
- [ ] Write unit tests

---
- [ ] [React](https://github.com/goodmind/protoapp-plugin-react) plugin
- [x] [Angular](https://github.com/goodmind/protoapp-plugin-angular) plugin
